services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:1313"
    networks:
      - mynetwork
    environment: 
      - VARIABLE_API=valor_variable_api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:2222"
    networks:
      - mynetwork
    environment: 
      - VARIABLE_FRONTEND=valor_variable_frontend
      
networks:
  mynetwork:
    driver: bridge
